# Generated by Django 5.1 on 2024-08-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
        ('users', '0002_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interests', to='users.user'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_interests', to='users.user'),
        ),
    ]
